### ISSUE TITLE
This code is only for training the dataset?

### ISSUE THREAD

**Issue by gayathripsg** [omidai/Predict-next-word#2]
Great job sir, Is this code is only for training the dataset?
i tried with this code sir, got only the output for training part. Is there any modifications is needed to get the result? can you please help me for further execution.
![image](https://user-images.githubusercontent.com/31529748/39137161-8cd0ab36-473a-11e8-8b35-89a08613a453.png)

**Comment by seyedsaeidmasoumzadeh** [comment]
I wrote this code long time ago, but as I remember yes you are trining the model on large text data and the model can predict P(next_word | a word). This is very useful in auto-suggestion task in search engines where you train the model in big corpus of queries

**Comment by talatccan** [comment]
Hi, at the first thank you.

I stucked in same thing. I trained my data and thats all. What should i do after it i dont know? As i understood it just trained and did not create any model.

How can i save model and predict next word?

**Comment by seyedsaeidmasoumzadeh** [comment]
Please use the new version of the code which I recently updated, it has a method to predict
