### ISSUE TITLE
multiple prediction

### ISSUE THREAD

**Issue by kamrul29** [omidai/Predict-next-word#3]
Your work is awesome,
Can you predict multiple words  and as well as for any length of text?

I want a dynamic system that will take input of a sentence of any length and predict 5 suggestions for the next word

Please help me

**Comment by seyedsaeidmasoumzadeh** [comment]
@kamrul29 Hi, the last layer is softmax so you can suggest the X number of words based on their probabilities, instead of using argmax to get the one which has the highest probability.
