### ISSUE TITLE
cannot find the file 'vocab/rev_vocab.json' 

### ISSUE THREAD

**Issue by steenn30** [omidai/Predict-next-word#4]
are you able to supply the .json files for this program? If not, do you know where I can acquire these files?

**Comment by abedelkarim** [comment]
Hello, i have the same problem. How do you get this file ? can you share the file with me please?

**Comment by seyedsaeidmasoumzadeh** [comment]
@steenn30 @abedelkarim Hi , the .json fils are created during the training (in data_sampling method). You need to run training before using them in the prediction
